spring:
  application.name: simple-mental-math-bot
  profiles.active: ${ENVIRONMENT_PROFILE_NAME:dev}
  cloud:
    vault:
      host: 192.168.88.248
      port: 8200
      scheme: http
      token: ${VAULT_TOKEN}
  config.import: vault://
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  prometheus:
    metrics:
      export:
        enabled: true
bot:
  name: simple_mental_math_bot
  token: ${bot.token}
